- name: list kind clusters
  shell:
    cmd: "../bin/kind get clusters"
    chdir: '{{ "{{" }} run_dir {{ "}}" }}/home'
  register: kind_clusters

- name: nuke kind cluster
  shell:
    cmd: '../bin/kind delete cluster --name {{ "{{" }} kernel.name | lower {{ "}}" }}'
    chdir: '{{ "{{" }} run_dir {{ "}}" }}/home'
  when: '"{{ "{{" }} kernel.name | lower {{ "}}" }}" in kind_clusters.stdout_lines'
