- name: prepare folders
  file:
    path: "{{ "{{" }} item {{ "}}" }}"
    state: directory
    recurse: yes
  with_items:
    - "{{ "{{" }} run_dir {{ "}}" }}/home/.kube"
    - "{{ "{{" }} run_dir {{ "}}" }}/var/k3s"
    - "{{ "{{" }} run_dir {{ "}}" }}/var/data"
    - "{{ "{{" }} run_dir {{ "}}" }}/var/data/volumes"

- name: start embedded k8s node
  community.docker.docker_container:
    state: started
    name: "{{ .kubecontext }}"
    image: "{{ .kubeImage }}"
    env:
      TZ: "Europe/Paris"
      K3S_TOKEN: "a_random_token"
      K3S_KUBECONFIG_OUTPUT: "/config/config"
      K3S_KUBECONFIG_MODE: "666"
    command:
      - server
      - --https-listen-port={{ .kubeApiPort }}
      - --node-name=single-node
      - --disable-cloud-controller
      - --prefer-bundled-bin
      - --default-local-storage-path=/data/volumes
    privileged: yes
   
    volumes:
      - "{{ "{{" }} run_dir {{ "}}" }}/var/k3s:/var/lib/rancher/k3s"
      - "{{ "{{" }} run_dir {{ "}}" }}/var/data:/data"
      - "{{ "{{" }} run_dir {{ "}}" }}/home/.kube:/config"
    ports:
      - "0.0.0.0:{{ .kubeApiPort }}:{{ .kubeApiPort }}/tcp"
    networks:
      - name: network_{{ .kubecontext }}
  until: "container_info.container.State.Health.Status == 'healthy'"
  register: container_info
  retries: 15
  delay: 10

- name: wait for kubeconfig file to be created
  ansible.builtin.wait_for:
    path: "{{ "{{" }} run_dir {{ "}}" }}/home/.kube/config"
    state: present
    timeout: 60
