- name: install tools
  become: yes
  apt:
    name:
      - openssl
      - apt-transport-https
      - ca-certificates
      - gnupg
      - curl
    state: present

# debut SSL TLS Ingress Cert
- name: ensure ca directory exists
  file:
    path: "{{ item }}"
    state: directory
    mode: 0700
  with_items:
    - "{{ site.tls.paths.secrets }}/ssl"

- name: private key_exists
  stat:
    path: "{{ site.tls.paths.secrets }}/ssl/{{ site.tls.ingress.domain }}.key"
  register: private_key_exists

- name: "generating SSL private key for {{ item.name }}"
  openssl_privatekey:
    path: "{{ site.tls.paths.secrets }}/ssl/{{ site.tls.ingress.domain }}.key"
    backup: yes
    size: "{{ site.tls.ingress.key.size }}"
    type: "{{ site.tls.ingress.key.type }}"
  register: private_key
  when: not private_key_exists.stat.exists

- name: generate a ssl wildcard certificate request
  openssl_csr:
    path: "{{ site.tls.paths.secrets }}/ssl/{{ site.tls.ingress.domain }}.csr"
    privatekey_path: "{{ site.tls.paths.secrets }}/ssl/{{ site.tls.ingress.domain }}.key"
    country_name: "{{ site.tls.ingress.info.country }}"
    state_or_province_name: "{{ site.tls.ingress.info.state }}"
    locality_name: "{{ site.tls.ingress.info.locality }}"
    organization_name: "{{ site.tls.ingress.info.organization }}"
    organizational_unit_name: "{{ site.tls.ingress.info.organization_unit }}"
    email_address: "{{ site.tls.ingress.info.email }}"
    common_name: "{{ site.tls.ingress.domain }}"
    subject_alt_name: "DNS:{{ site.tls.ingress.domain }}"
    use_common_name_for_san: no
  when: not private_key_exists.stat.exists and private_key.changed

- name: read ca password file
  slurp:
    src: "{{ site.tls.paths.secrets }}/ca/{{ site.tls.ca.domain }}.pwd"
  register: pwd_value
  when: not private_key_exists.stat.exists

- name: sign ssl certificate with CA authority
  openssl_certificate:
    path: "{{ site.tls.paths.secrets }}/ssl/{{ site.tls.ingress.domain }}.crt"
    csr_path: "{{ site.tls.paths.secrets }}/ssl/{{ site.tls.ingress.domain }}.csr"
    ownca_path: "{{ site.tls.paths.secrets }}/ca/{{ site.tls.ca.domain }}.crt"
    ownca_privatekey_path: "{{ site.tls.paths.secrets }}/ca/{{ site.tls.ca.domain }}.key"
    ownca_privatekey_passphrase: "{{ pwd_value.content | b64decode }}"
    ownca_not_after: "{{ site.tls.ingress.expiration }}"
    provider: ownca
  when: not private_key_exists.stat.exists and private_key.changed
