host:
  address: 127.0.0.1
  ingress:
    address: 127.0.0.1
    port: 8080
    rootUrl: http://127.0.0.1:8080
    # tls:
    #   port: 8443
    #   cert: "etc/pki/ssl/s.sample.local.crt"
    #   key: "etc/pki/ssl/s.sample.local.key"
    auth:
      defaultAccess: "public"
      public:
        enabled: true
      authenticated:
        enabled: false
      admin:
        enabled: false
  compute:
    enabled: true
    containers:
      engine: podman
      port:
        start: 59000
        end: 59999
    kubernetes:
      useEmbedded: true
      kubeConfig: "{{ run_dir }}/home/.kube/config"
      kubeApiPort: 46443
