host:
  address: 127.0.0.1
  ingress:
    address: 127.0.0.1
    port: 28080
    rootUrl: https://localhost:28443
    tls:
      port: 28443
      cert: "etc/pki/ssl/s.sample.local.crt"
      key: "etc/pki/ssl/s.sample.local.key"
    auth:
      default_access: "public"
      public:
        enabled: true
      authenticated:
        enabled: true
        login_url: "/auth/users/login"
        verify_url: "/auth/users/verify"
        redirect_param: "redirect"
  compute:
    enabled: true
    containers:
      engine: docker
      port:
        start: 25000
        end: 25999
    kubernetes:
      embedded:
        enabled: true
        image: docker.io/rancher/k3s:v1.30.11-k3s1
